### ISSUE TITLE
Very Nice Work! And question about difftool

### ISSUE THREAD

**Issue by AmnonDrory** [ericpruitt/sshfsexec#5]
Hi,
Thanks for sharing this, it is quite useful!
I have an issue with git difftool, which I use with Beyond Compare (BC). When I run difftool (either in an ssh session or with sshfsexec), it starts the BC that's installed on the remote computer. That's s l o w . Any idea how I can instead get my local BC to perform the comparsions?
Thanks!
Amnon

**Comment by ericpruitt** [comment]
That's not something you can resolve with sshfsexec.
